<?php
declare(strict_types=1);
require_once dirname(__DIR__,2).'/includes/news/bootstrap.php';
require_once dirname(__DIR__,2).'/classes/News/RecommendationService.php';
require_once dirname(__DIR__,2).'/classes/News/AlertToken.php';
$userId=newsRequireCustomerJson();$pdo=newsPdo('web');$action=(string)($_GET['action']??$_POST['action']??'bootstrap');
try{
 if($_SERVER['REQUEST_METHOD']!=='GET'){$data=newsRequestData();$token=$_SERVER['HTTP_X_CSRF_TOKEN']??($data['csrf_token']??'');if(!NewsSupport::verifyCsrf($token))newsJson(['success'=>false,'message'=>'Your security token is invalid.'],403);}
 if($_SERVER['REQUEST_METHOD']!=='GET')newsRateLimit('customer_news_write',40,60);
 switch($action){
  case 'bootstrap':
   $categories=$pdo->query('SELECT id,category_name,category_slug,news_type FROM news_categories WHERE is_active=1 ORDER BY display_order,category_name')->fetchAll(PDO::FETCH_ASSOC);
   $entities=$pdo->query('SELECT id,entity_name,entity_slug,entity_type FROM news_entities WHERE is_active=1 ORDER BY entity_type,entity_name LIMIT 1000')->fetchAll(PDO::FETCH_ASSOC);
   $keywords=$pdo->query('SELECT id,keyword_name,keyword_slug,keyword_type FROM news_keywords WHERE is_active=1 ORDER BY keyword_name LIMIT 1000')->fetchAll(PDO::FETCH_ASSOC);
   $stmt=$pdo->prepare('SELECT * FROM user_news_preferences WHERE user_id=:user AND is_active=1');$stmt->execute([':user'=>$userId]);$preferences=$stmt->fetchAll(PDO::FETCH_ASSOC);
   $stmt=$pdo->prepare('SELECT * FROM user_news_settings WHERE user_id=:user');$stmt->execute([':user'=>$userId]);$settings=$stmt->fetch(PDO::FETCH_ASSOC)?:['personalization_enabled'=>1,'history_enabled'=>1,'news_type_preference'=>'both'];
   $stmt=$pdo->prepare('SELECT id,alert_name,frequency,delivery_method,is_active,last_sent_at FROM user_news_alerts WHERE user_id=:user ORDER BY id DESC');$stmt->execute([':user'=>$userId]);
   newsJson(['success'=>true,'csrf_token'=>NewsSupport::csrfToken(),'categories'=>$categories,'entities'=>$entities,'keywords'=>$keywords,'preferences'=>$preferences,'settings'=>$settings,'alerts'=>$stmt->fetchAll(PDO::FETCH_ASSOC)]);
  case 'feed':newsJson(['success'=>true,'articles'=>(new NewsRecommendationService($pdo))->feed($userId,max(1,(int)($_GET['page']??1)),12)]);
  case 'saved':
   $stmt=$pdo->prepare("SELECT a.*,s.source_name,c.category_name,sa.saved_at,sa.notes FROM user_saved_news_articles sa JOIN news_articles a ON a.id=sa.article_id LEFT JOIN news_sources s ON s.id=a.source_id LEFT JOIN news_categories c ON c.id=a.category_id WHERE sa.user_id=:user AND a.status='published' ORDER BY ".(($_GET['sort']??'saved')==='published'?'a.published_at':'sa.saved_at').' DESC');$stmt->execute([':user'=>$userId]);newsJson(['success'=>true,'articles'=>$stmt->fetchAll(PDO::FETCH_ASSOC)]);
  case 'save_preference':
   $data=newsRequestData();$type=$data['preference_type']??'';if(!in_array($type,['entity','category','keyword','cruise','resort','destination','port'],true))throw new InvalidArgumentException('Invalid preference type.');
   $entity=(int)($data['entity_id']??0)?:null;$category=(int)($data['category_id']??0)?:null;$keyword=(int)($data['keyword_id']??0)?:null;$value=NewsSupport::cleanText($data['preference_value']??'',255)?:null;if(!$entity&&!$category&&!$keyword&&!$value)throw new InvalidArgumentException('Choose an interest.');
   $key=$type.':'.($entity?'entity-'.$entity:($category?'category-'.$category:($keyword?'keyword-'.$keyword:'value-'.NewsSupport::slug((string)$value))));$stmt=$pdo->prepare('INSERT INTO user_news_preferences(user_id,preference_type,preference_key,preference_value,entity_id,category_id,keyword_id,priority_level,is_active) VALUES(:user,:type,:key,:value,:entity,:category,:keyword,:priority,1) ON DUPLICATE KEY UPDATE priority_level=VALUES(priority_level),is_active=1');$stmt->execute([':user'=>$userId,':type'=>$type,':key'=>$key,':value'=>$value,':entity'=>$entity,':category'=>$category,':keyword'=>$keyword,':priority'=>max(1,min(3,(int)($data['priority_level']??1)))]);newsJson(['success'=>true,'message'=>'Interest followed.']);
  case 'remove_preference':$data=newsRequestData();$pdo->prepare('DELETE FROM user_news_preferences WHERE id=:id AND user_id=:user')->execute([':id'=>(int)($data['id']??0),':user'=>$userId]);newsJson(['success'=>true,'message'=>'Interest removed.']);
  case 'save_settings':$data=newsRequestData();$type=in_array($data['news_type_preference']??'', ['cruise','resort','both'],true)?$data['news_type_preference']:'both';$pdo->prepare('INSERT INTO user_news_settings(user_id,personalization_enabled,history_enabled,news_type_preference) VALUES(:user,:personalization,:history,:type) ON DUPLICATE KEY UPDATE personalization_enabled=VALUES(personalization_enabled),history_enabled=VALUES(history_enabled),news_type_preference=VALUES(news_type_preference)')->execute([':user'=>$userId,':personalization'=>!empty($data['personalization_enabled'])?1:0,':history'=>!empty($data['history_enabled'])?1:0,':type'=>$type]);newsJson(['success'=>true,'message'=>'News settings saved.']);
  case 'save_article':$data=newsRequestData();$id=(int)($data['article_id']??0);$notes=NewsSupport::cleanText($data['notes']??'',2000);$pdo->prepare('INSERT INTO user_saved_news_articles(user_id,article_id,notes) SELECT :user,id,:notes FROM news_articles WHERE id=:id AND status="published" ON DUPLICATE KEY UPDATE notes=VALUES(notes),saved_at=NOW()')->execute([':user'=>$userId,':id'=>$id,':notes'=>$notes]);newsJson(['success'=>true,'message'=>'Article saved.']);
  case 'unsave_article':$data=newsRequestData();$pdo->prepare('DELETE FROM user_saved_news_articles WHERE user_id=:user AND article_id=:id')->execute([':user'=>$userId,':id'=>(int)($data['article_id']??0)]);newsJson(['success'=>true,'message'=>'Article removed.']);
  case 'hide_article':$data=newsRequestData();$pdo->prepare('INSERT IGNORE INTO user_news_hidden_articles(user_id,article_id,reason) VALUES(:user,:id,:reason)')->execute([':user'=>$userId,':id'=>(int)($data['article_id']??0),':reason'=>NewsSupport::cleanText($data['reason']??'',255)]);newsJson(['success'=>true,'message'=>'Recommendation hidden.']);
  case 'record_view':$data=newsRequestData();$settings=$pdo->prepare('SELECT history_enabled FROM user_news_settings WHERE user_id=:user');$settings->execute([':user'=>$userId]);if($settings->fetchColumn()!==0)$pdo->prepare('INSERT INTO user_news_article_views(user_id,article_id,view_source,session_reference) VALUES(:user,:article,:source,:session)')->execute([':user'=>$userId,':article'=>(int)($data['article_id']??0),':source'=>NewsSupport::cleanText($data['view_source']??'feed',40),':session'=>hash('sha256',session_id())]);newsJson(['success'=>true]);
  case 'clear_history':$pdo->prepare('DELETE FROM user_news_article_views WHERE user_id=:user')->execute([':user'=>$userId]);newsJson(['success'=>true,'message'=>'News viewing history deleted.']);
  case 'create_alert':$data=newsRequestData();$frequency=in_array($data['frequency']??'', ['daily','weekly','monthly','breaking','disabled'],true)?$data['frequency']:'weekly';$pdo->prepare('INSERT INTO user_news_alerts(user_id,alert_name,frequency,delivery_method,is_active,unsubscribe_token_hash) VALUES(:user,:name,:frequency,"email",:active,:token)')->execute([':user'=>$userId,':name'=>NewsSupport::cleanText($data['alert_name']??'My travel news',180),':frequency'=>$frequency,':active'=>$frequency==='disabled'?0:1,':token'=>hash('sha256',random_bytes(32))]);$alertId=(int)$pdo->lastInsertId();$token=NewsAlertToken::create($alertId);$pdo->prepare('UPDATE user_news_alerts SET unsubscribe_token_hash=:hash WHERE id=:id')->execute([':hash'=>hash('sha256',$token),':id'=>$alertId]);newsJson(['success'=>true,'message'=>'Digest preference created.']);
  default:newsJson(['success'=>false,'message'=>'Unknown account news action.'],404);
 }
}catch(InvalidArgumentException $e){newsJson(['success'=>false,'message'=>$e->getMessage()],422);}catch(Throwable $e){error_log('Customer news failed: '.$e->getMessage());newsJson(['success'=>false,'message'=>'The news request could not be completed. Check that all news migrations have run.'],500);}
