<?php
declare(strict_types=1);
require_once dirname(__DIR__,3).'/includes/news/bootstrap.php';
require_once dirname(__DIR__,3).'/classes/News/NewsImporter.php';
require_once dirname(__DIR__,3).'/classes/News/SummaryService.php';
require_once dirname(__DIR__,3).'/classes/News/JobQueue.php';
$userId=newsRequireAdminJson(); $pdo=newsPdo('admin'); $action=(string)($_GET['action']??$_POST['action']??'dashboard');

try {
    if($_SERVER['REQUEST_METHOD']!=='GET') { $data=newsRequestData(); $token=$_SERVER['HTTP_X_CSRF_TOKEN']??($data['csrf_token']??''); if(!NewsSupport::verifyCsrf($token))newsJson(['success'=>false,'message'=>'Your security token is invalid. Refresh and try again.'],403); }
    switch($action){
        case 'bootstrap':
            $sources=$pdo->query('SELECT * FROM news_sources ORDER BY source_name')->fetchAll(PDO::FETCH_ASSOC);
            $categories=$pdo->query('SELECT * FROM news_categories ORDER BY display_order,category_name')->fetchAll(PDO::FETCH_ASSOC);
            $entities=$pdo->query('SELECT * FROM news_entities WHERE is_active=1 ORDER BY entity_type,entity_name LIMIT 1000')->fetchAll(PDO::FETCH_ASSOC);try{$newsletters=$pdo->query('SELECT id,newsletter_name,status FROM news_newsletters ORDER BY id DESC LIMIT 100')->fetchAll(PDO::FETCH_ASSOC);}catch(PDOException){$newsletters=[];}
            newsJson(['success'=>true,'csrf_token'=>NewsSupport::csrfToken(),'sources'=>$sources,'categories'=>$categories,'entities'=>$entities,'newsletters'=>$newsletters]);
        case 'dashboard':
            $metrics=[];
            $queries=['active_sources'=>'SELECT COUNT(*) FROM news_sources WHERE is_active=1','imported_today'=>'SELECT COUNT(*) FROM news_articles WHERE DATE(retrieved_at)=CURDATE()','pending'=>'SELECT COUNT(*) FROM news_articles WHERE status IN("imported","pending_review")','published_today'=>'SELECT COUNT(*) FROM news_articles WHERE status="published" AND DATE(published_at)=CURDATE()','duplicates'=>'SELECT COUNT(*) FROM news_articles WHERE is_duplicate=1','failed_imports'=>'SELECT COUNT(*) FROM news_import_logs WHERE status="failed" AND started_at>=DATE_SUB(NOW(),INTERVAL 7 DAY)'];
            foreach($queries as $key=>$sql)$metrics[$key]=(int)$pdo->query($sql)->fetchColumn();
            $metrics['recent_imports']=$pdo->query('SELECT l.*,s.source_name FROM news_import_logs l LEFT JOIN news_sources s ON s.id=l.source_id ORDER BY l.id DESC LIMIT 8')->fetchAll(PDO::FETCH_ASSOC);
            try{$metrics['personalization']=['active_preferences'=>(int)$pdo->query('SELECT COUNT(*) FROM user_news_preferences WHERE is_active=1')->fetchColumn(),'saved_articles'=>(int)$pdo->query('SELECT COUNT(*) FROM user_saved_news_articles')->fetchColumn(),'article_views'=>(int)$pdo->query('SELECT COUNT(*) FROM user_news_article_views')->fetchColumn(),'digest_failures'=>(int)$pdo->query("SELECT COUNT(*) FROM user_news_digest_history WHERE status='failed'")->fetchColumn(),'top_categories'=>$pdo->query('SELECT c.category_name,COUNT(*) total FROM user_news_preferences p JOIN news_categories c ON c.id=p.category_id WHERE p.is_active=1 GROUP BY c.id ORDER BY total DESC LIMIT 5')->fetchAll(PDO::FETCH_ASSOC),'top_entities'=>$pdo->query('SELECT e.entity_name,COUNT(*) total FROM user_news_preferences p JOIN news_entities e ON e.id=p.entity_id WHERE p.is_active=1 GROUP BY e.id ORDER BY total DESC LIMIT 5')->fetchAll(PDO::FETCH_ASSOC)];}catch(PDOException){$metrics['personalization']=null;}
            newsJson(['success'=>true,'metrics'=>$metrics]);
        case 'articles':
            $status=(string)($_GET['status']??'pending_review'); $allowed=['imported','pending_review','approved','scheduled','published','rejected','archived','all'];
            if(!in_array($status,$allowed,true))$status='pending_review'; $params=[];$where=[];
            if($status!=='all'){$where[]='a.status=:status';$params[':status']=$status;} if(!empty($_GET['q'])){$where[]='(a.headline LIKE :q1 OR s.source_name LIKE :q2)';$query='%'.mb_substr((string)$_GET['q'],0,100).'%';$params[':q1']=$query;$params[':q2']=$query;}
            if(in_array($_GET['type']??'', ['cruise','resort'],true)){$where[]='a.news_type=:type';$params[':type']=$_GET['type'];}
            $sql='SELECT a.*,s.source_name,c.category_name,(SELECT MAX(similarity_score) FROM news_article_relations r WHERE r.article_id=a.id) similar_score,(SELECT GROUP_CONCAT(k.keyword_name ORDER BY k.keyword_name SEPARATOR ", ") FROM news_article_keywords ak JOIN news_keywords k ON k.id=ak.keyword_id WHERE ak.article_id=a.id) keywords,(SELECT GROUP_CONCAT(ae.entity_id ORDER BY ae.entity_id) FROM news_article_entities ae WHERE ae.article_id=a.id) entity_ids FROM news_articles a LEFT JOIN news_sources s ON s.id=a.source_id LEFT JOIN news_categories c ON c.id=a.category_id'.($where?' WHERE '.implode(' AND ',$where):'').' ORDER BY a.id DESC LIMIT 200';
            $stmt=$pdo->prepare($sql);$stmt->execute($params);newsJson(['success'=>true,'articles'=>$stmt->fetchAll(PDO::FETCH_ASSOC)]);
        case 'save_source':
            $data=newsRequestData();$id=(int)($data['id']??0);$name=trim((string)($data['source_name']??''));$feed=trim((string)($data['feed_url']??''));
            if($name===''||$feed==='')throw new InvalidArgumentException('Source name and feed URL are required.');NewsUrlGuard::assertPublicHttpUrl($feed);
            $connectorConfig=trim((string)($data['connector_config_json']??''));if($connectorConfig!==''){try{json_decode($connectorConfig,true,32,JSON_THROW_ON_ERROR);}catch(JsonException){throw new InvalidArgumentException('Connector configuration must be valid JSON.');}}
            $values=[':name'=>mb_substr($name,0,180),':slug'=>NewsSupport::slug($name),':type'=>in_array($data['source_type']??'', ['rss','atom','api','manual','tourism_board','cruise_line','resort','publication'],true)?$data['source_type']:'rss',':website'=>filter_var($data['website_url']??'',FILTER_VALIDATE_URL)?$data['website_url']:null,':feed'=>$feed,':news_type'=>in_array($data['default_news_type']??'', ['cruise','resort'],true)?$data['default_news_type']:'cruise',':category'=>(int)($data['default_category_id']??0)?:null,':active'=>!empty($data['is_active'])?1:0,':image'=>!empty($data['image_reuse_allowed'])?1:0,':minutes'=>max(15,min(10080,(int)($data['fetch_frequency_minutes']??360)))];
            if($id){$values[':id']=$id;$pdo->prepare('UPDATE news_sources SET source_name=:name,source_slug=:slug,source_type=:type,website_url=:website,feed_url=:feed,default_news_type=:news_type,default_category_id=:category,is_active=:active,image_reuse_allowed=:image,fetch_frequency_minutes=:minutes WHERE id=:id')->execute($values);}else{$pdo->prepare('INSERT INTO news_sources(source_name,source_slug,source_type,website_url,feed_url,default_news_type,default_category_id,is_active,image_reuse_allowed,fetch_frequency_minutes) VALUES(:name,:slug,:type,:website,:feed,:news_type,:category,:active,:image,:minutes)')->execute($values);$id=(int)$pdo->lastInsertId();}
            try{$pdo->prepare('UPDATE news_sources SET connector_config_json=:config,trust_score=:trust,priority_score=:priority,default_relevance_score=:relevance,is_official_source=:official,requires_manual_review=:manual WHERE id=:id')->execute([':config'=>$connectorConfig?:null,':trust'=>max(0,min(100,(float)($data['trust_score']??50))),':priority'=>max(0,min(100,(float)($data['priority_score']??50))),':relevance'=>max(0,min(100,(float)($data['default_relevance_score']??50))),':official'=>!empty($data['is_official_source'])?1:0,':manual'=>!empty($data['requires_manual_review'])?1:0,':id'=>$id]);}catch(PDOException){}
            newsJson(['success'=>true,'id'=>$id,'message'=>'Source saved.']);
        case 'test_source':case 'import_source':
            newsRateLimit('admin_import',10,300);
            $data=newsRequestData();$sourceId=(int)($data['source_id']??0);if($sourceId<1)throw new InvalidArgumentException('Select a source.');$importer=new NewsImporter($pdo);
            if($action==='test_source')newsJson(['success'=>true,'preview'=>$importer->importSource($sourceId,'manual',$userId,true)]);
            newsJson(['success'=>true,'counts'=>$importer->importSource($sourceId,'manual',$userId,false),'message'=>'Import completed.']);
        case 'save_article':
            $data=newsRequestData();$id=(int)($data['id']??0);$headline=NewsSupport::cleanText($data['headline']??'',500);if(!$id||$headline==='')throw new InvalidArgumentException('Article and headline are required.');
            $old=$pdo->prepare('SELECT status FROM news_articles WHERE id=:id');$old->execute([':id'=>$id]);$previous=$old->fetchColumn();if($previous===false)throw new InvalidArgumentException('Article not found.');
            $status=in_array($data['status']??'', ['pending_review','approved','scheduled','published','rejected','archived'],true)?$data['status']:'pending_review';$published=NewsSupport::dateOrNull($data['published_at']??null);if($status==='published'&&!$published)$published=date('Y-m-d H:i:s');
            $stmt=$pdo->prepare('UPDATE news_articles SET headline=:headline,slug=:slug,summary=:summary,editorial_summary=:editorial,news_type=:type,category_id=:category,status=:status,review_status=:review,is_featured=:featured,is_breaking=:breaking,is_duplicate=:duplicate,duplicate_of_article_id=:duplicate_of,image_local_path=:image,image_alt_text=:alt,image_attribution=:attribution,image_license_notes=:license,image_usage_approved=:image_approved,meta_title=:meta_title,meta_description=:meta_description,published_at=:published,published_by_user_id=IF(:status2="published",:user,published_by_user_id),reviewed_at=NOW(),reviewed_by_user_id=:user2,admin_notes=:notes WHERE id=:id');
            $stmt->execute([':headline'=>$headline,':slug'=>NewsSupport::uniqueSlug($pdo,$data['slug']??$headline,$id),':summary'=>NewsSupport::cleanText($data['summary']??'',1000),':editorial'=>NewsSupport::cleanText($data['editorial_summary']??'',10000),':type'=>in_array($data['news_type']??'', ['cruise','resort'],true)?$data['news_type']:'cruise',':category'=>(int)($data['category_id']??0)?:null,':status'=>$status,':review'=>$status==='pending_review'?'in_review':'reviewed',':featured'=>!empty($data['is_featured'])?1:0,':breaking'=>!empty($data['is_breaking'])?1:0,':duplicate'=>!empty($data['is_duplicate'])?1:0,':duplicate_of'=>(int)($data['duplicate_of_article_id']??0)?:null,':image'=>trim((string)($data['image_local_path']??''))?:null,':alt'=>NewsSupport::cleanText($data['image_alt_text']??'',500),':attribution'=>NewsSupport::cleanText($data['image_attribution']??'',500),':license'=>NewsSupport::cleanText($data['image_license_notes']??'',2000),':image_approved'=>!empty($data['image_usage_approved'])?1:0,':meta_title'=>NewsSupport::cleanText($data['meta_title']??'',255),':meta_description'=>NewsSupport::cleanText($data['meta_description']??'',320),':published'=>$published,':status2'=>$status,':user'=>$userId,':user2'=>$userId,':notes'=>NewsSupport::cleanText($data['admin_notes']??'',5000),':id'=>$id]);
            $pdo->prepare('DELETE FROM news_article_keywords WHERE article_id=:id')->execute([':id'=>$id]);foreach(array_unique(array_filter(array_map('trim',explode(',',(string)($data['keywords']??''))))) as $keyword){$name=NewsSupport::cleanText($keyword,120);if($name==='')continue;$slug=NewsSupport::slug($name);$pdo->prepare('INSERT INTO news_keywords(keyword_name,keyword_slug) VALUES(:name,:slug) ON DUPLICATE KEY UPDATE keyword_name=VALUES(keyword_name)')->execute([':name'=>$name,':slug'=>$slug]);$keywordStmt=$pdo->prepare('SELECT id FROM news_keywords WHERE keyword_slug=:slug');$keywordStmt->execute([':slug'=>$slug]);$keywordId=(int)$keywordStmt->fetchColumn();$pdo->prepare('INSERT IGNORE INTO news_article_keywords(article_id,keyword_id) VALUES(:article,:keyword)')->execute([':article'=>$id,':keyword'=>$keywordId]);}
            $pdo->prepare('DELETE FROM news_article_entities WHERE article_id=:id')->execute([':id'=>$id]);$entityIds=$data['entity_ids']??[];if(!is_array($entityIds))$entityIds=array_filter(array_map('intval',explode(',',(string)$entityIds)));foreach(array_unique(array_map('intval',$entityIds)) as $entityId)if($entityId>0)$pdo->prepare('INSERT IGNORE INTO news_article_entities(article_id,entity_id,relationship_type) SELECT :article,id,"mentioned" FROM news_entities WHERE id=:entity AND is_active=1')->execute([':article'=>$id,':entity'=>$entityId]);
            $pdo->prepare('INSERT INTO news_article_history(article_id,changed_by_user_id,action_type,previous_status,new_status,change_details) VALUES(:id,:user,"review",:previous,:new,"Article reviewed in administrator interface")')->execute([':id'=>$id,':user'=>$userId,':previous'=>$previous,':new'=>$status]);newsJson(['success'=>true,'message'=>'Article saved.']);
        case 'manual_article':
            $data=newsRequestData();$headline=NewsSupport::cleanText($data['headline']??'',500);$url=trim((string)($data['source_url']??''));if($headline===''||!filter_var($url,FILTER_VALIDATE_URL))throw new InvalidArgumentException('Headline and a valid source URL are required.');
            $normalized=NewsSupport::normalizeUrl($url);$pdo->prepare('INSERT INTO news_articles(source_id,news_type,category_id,headline,slug,source_headline,summary,source_url,canonical_url,status,review_status,content_hash,normalized_url_hash,relevance_score) VALUES(:source,:type,:category,:headline,:slug,:headline2,:summary,:url,:canonical,"pending_review","unreviewed",:content,:urlhash,50)')->execute([':source'=>(int)($data['source_id']??0)?:null,':type'=>in_array($data['news_type']??'', ['cruise','resort'],true)?$data['news_type']:'cruise',':category'=>(int)($data['category_id']??0)?:null,':headline'=>$headline,':slug'=>NewsSupport::uniqueSlug($pdo,$headline),':headline2'=>$headline,':summary'=>NewsSupport::cleanText($data['summary']??'',1000),':url'=>$url,':canonical'=>$normalized,':content'=>hash('sha256',strtolower($headline.'|'.($data['summary']??''))),':urlhash'=>hash('sha256',$normalized)]);newsJson(['success'=>true,'message'=>'Manual article added to review.']);
        case 'save_category':
            $data=newsRequestData();$name=NewsSupport::cleanText($data['category_name']??'',120);if($name==='')throw new InvalidArgumentException('Category name is required.');$values=[':parent'=>(int)($data['parent_id']??0)?:null,':name'=>$name,':slug'=>NewsSupport::slug($name),':type'=>in_array($data['news_type']??'', ['cruise','resort','both'],true)?$data['news_type']:'both',':display'=>max(0,(int)($data['display_order']??0)),':active'=>!empty($data['is_active'])?1:0];$categoryId=(int)($data['id']??0);if($categoryId){$values[':id']=$categoryId;$pdo->prepare('UPDATE news_categories SET parent_id=:parent,category_name=:name,category_slug=:slug,news_type=:type,display_order=:display,is_active=:active WHERE id=:id')->execute($values);}else{$pdo->prepare('INSERT INTO news_categories(parent_id,category_name,category_slug,news_type,display_order,is_active) VALUES(:parent,:name,:slug,:type,:display,:active)')->execute($values);}newsJson(['success'=>true,'message'=>$categoryId?'Category updated.':'Category added.']);
        case 'queue_summary':
            $data=newsRequestData();$id=(int)($data['article_id']??0);(new NewsJobQueue($pdo))->enqueue('generate_summary',['article_id'=>$id],70);$pdo->prepare("UPDATE news_articles SET generated_summary_status='queued' WHERE id=:id")->execute([':id'=>$id]);newsJson(['success'=>true,'message'=>'Summary queued for review.']);
        case 'create_newsletter':
            $data=newsRequestData();$name=NewsSupport::cleanText($data['newsletter_name']??'',180);if($name==='')throw new InvalidArgumentException('Newsletter name is required.');$pdo->prepare('INSERT INTO news_newsletters(newsletter_name,newsletter_subject,newsletter_type,created_by_user_id) VALUES(:name,:subject,:type,:user)')->execute([':name'=>$name,':subject'=>NewsSupport::cleanText($data['newsletter_subject']??$name,255),':type'=>in_array($data['newsletter_type']??'', ['cruise','resort','both'],true)?$data['newsletter_type']:'both',':user'=>$userId]);newsJson(['success'=>true,'message'=>'Newsletter draft created.']);
        case 'save_entity':
            $data=newsRequestData();$name=NewsSupport::cleanText($data['entity_name']??'',180);$type=NewsSupport::slug($data['entity_type']??'');if($name===''||$type==='news-story')throw new InvalidArgumentException('Entity name and type are required.');$pdo->prepare('INSERT INTO news_entities(entity_type,entity_name,entity_slug,description) VALUES(:type,:name,:slug,:description) ON DUPLICATE KEY UPDATE entity_name=VALUES(entity_name),description=VALUES(description),is_active=1')->execute([':type'=>$type,':name'=>$name,':slug'=>NewsSupport::slug($name),':description'=>NewsSupport::cleanText($data['description']??'',2000)]);newsJson(['success'=>true,'message'=>'Entity saved.']);
        case 'save_rule':
            $data=newsRequestData();$value=NewsSupport::cleanText($data['match_value']??'',255);if($value==='')throw new InvalidArgumentException('Rule match text is required.');$pdo->prepare('INSERT INTO news_classification_rules(rule_name,match_type,match_value,suggested_news_type,suggested_category_id,score_adjustment) VALUES(:name,"contains",:value,:type,:category,:score)')->execute([':name'=>NewsSupport::cleanText($data['rule_name']??$value,160),':value'=>strtolower($value),':type'=>in_array($data['suggested_news_type']??'', ['cruise','resort'],true)?$data['suggested_news_type']:null,':category'=>(int)($data['suggested_category_id']??0)?:null,':score'=>max(-100,min(100,(float)($data['score_adjustment']??10)))]);newsJson(['success'=>true,'message'=>'Classification rule saved.']);
        case 'create_cluster':
            $data=newsRequestData();$articleIds=array_values(array_unique(array_filter(array_map('intval',$data['article_ids']??[]))));if(count($articleIds)<2)throw new InvalidArgumentException('Choose at least two articles.');$primary=(int)($data['primary_article_id']??$articleIds[0]);$pdo->beginTransaction();$pdo->prepare('INSERT INTO news_story_clusters(cluster_title,primary_article_id,confidence_score) VALUES(:title,:primary,:confidence)')->execute([':title'=>NewsSupport::cleanText($data['cluster_title']??'Related coverage',500),':primary'=>$primary,':confidence'=>max(0,min(100,(float)($data['confidence_score']??75)))]);$cluster=(int)$pdo->lastInsertId();foreach($articleIds as $articleId)$pdo->prepare('INSERT INTO news_story_cluster_articles(cluster_id,article_id,relationship_type) VALUES(:cluster,:article,:type)')->execute([':cluster'=>$cluster,':article'=>$articleId,':type'=>$articleId===$primary?'primary':'coverage']);$pdo->commit();newsJson(['success'=>true,'message'=>'Story cluster created.','id'=>$cluster]);
        case 'bulk_articles':
            $data=newsRequestData();$ids=array_values(array_unique(array_filter(array_map('intval',$data['article_ids']??[]))));$status=$data['status']??'';if(!$ids||!in_array($status,['approved','published','rejected','archived'],true))throw new InvalidArgumentException('Choose articles and a valid bulk action.');$placeholders=implode(',',array_fill(0,count($ids),'?'));$stmt=$pdo->prepare("UPDATE news_articles SET status=?,review_status='reviewed',reviewed_at=NOW(),reviewed_by_user_id=?,published_at=IF(?='published',COALESCE(published_at,NOW()),published_at) WHERE id IN ({$placeholders})");$stmt->execute(array_merge([$status,$userId,$status],$ids));foreach($ids as $id)$pdo->prepare('INSERT INTO news_article_history(article_id,changed_by_user_id,action_type,new_status,change_details) VALUES(:id,:user,"bulk_action",:status,"Bulk editorial action")')->execute([':id'=>$id,':user'=>$userId,':status'=>$status]);newsJson(['success'=>true,'message'=>count($ids).' articles updated.']);
        case 'newsletter_add_articles':
            $data=newsRequestData();$newsletter=(int)($data['newsletter_id']??0);$ids=array_values(array_unique(array_filter(array_map('intval',$data['article_ids']??[]))));if(!$newsletter||!$ids)throw new InvalidArgumentException('Newsletter and article IDs are required.');foreach($ids as $order=>$id)$pdo->prepare('INSERT INTO news_newsletter_articles(newsletter_id,article_id,display_order) SELECT :newsletter,id,:display FROM news_articles WHERE id=:article AND status="published" ON DUPLICATE KEY UPDATE display_order=VALUES(display_order)')->execute([':newsletter'=>$newsletter,':article'=>$id,':display'=>$order+1]);newsJson(['success'=>true,'message'=>'Articles added to newsletter.']);
        default: newsJson(['success'=>false,'message'=>'Unknown news action.'],404);
    }
} catch(InvalidArgumentException $e){if($pdo->inTransaction())$pdo->rollBack();newsJson(['success'=>false,'message'=>$e->getMessage()],422);}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();error_log('Admin news action failed: '.$e->getMessage());newsJson(['success'=>false,'message'=>'The news action could not be completed. Check that all news migrations have run.'],500);}
