<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli'){http_response_code(404);exit;}
$root=dirname(__DIR__);require_once $root.'/config/env.php';require_once $root.'/classes/News/RecommendationService.php';require_once $root.'/classes/News/AlertToken.php';
try{$pdo=normanCreateDatabaseConnection('admin');$lock=(int)$pdo->query("SELECT GET_LOCK('norman_news_digest',0)")->fetchColumn();if($lock!==1){fwrite(STDERR,"Another digest worker is running.\n");exit(2);}
 $alerts=$pdo->query("SELECT a.*,u.email_address FROM user_news_alerts a JOIN users u ON u.id=a.user_id WHERE a.is_active=1 AND ((a.frequency='daily' AND (a.last_sent_at IS NULL OR a.last_sent_at<DATE_SUB(NOW(),INTERVAL 1 DAY))) OR (a.frequency='weekly' AND (a.last_sent_at IS NULL OR a.last_sent_at<DATE_SUB(NOW(),INTERVAL 7 DAY))) OR (a.frequency='monthly' AND (a.last_sent_at IS NULL OR a.last_sent_at<DATE_SUB(NOW(),INTERVAL 1 MONTH))) OR a.frequency='breaking') LIMIT 100")->fetchAll(PDO::FETCH_ASSOC);$sent=0;
 foreach($alerts as $alert){$fallback=$alert['frequency']==='monthly'?'-1 month':($alert['frequency']==='daily'?'-1 day':'-7 days');$start=$alert['last_sent_at']?:date('Y-m-d H:i:s',strtotime($fallback));$articles=(new NewsRecommendationService($pdo))->feed((int)$alert['user_id'],1,50);$history=$pdo->prepare('SELECT article_ids_json FROM user_news_digest_history WHERE alert_id=:alert AND status IN("sent","exported","prepared") AND period_end>=DATE_SUB(NOW(),INTERVAL 90 DAY)');$history->execute([':alert'=>$alert['id']]);$previous=[];foreach($history->fetchAll(PDO::FETCH_COLUMN) as $json)$previous=array_merge($previous,json_decode($json,true)?:[]);$articles=array_values(array_filter($articles,fn($a)=>!in_array((int)$a['id'],array_map('intval',$previous),true)&&($alert['frequency']!=='breaking'||!empty($a['is_breaking']))));$articles=array_slice($articles,0,12);$ids=array_column($articles,'id');if(!$ids)continue;$token=NewsAlertToken::create((int)$alert['id']);$html='<!doctype html><html><body><h1>'.htmlspecialchars($alert['alert_name'],ENT_QUOTES,'UTF-8').'</h1>';foreach($articles as $a)$html.='<h2><a href="https://www.normanandcompany.com/news.php?article='.rawurlencode($a['slug']).'">'.htmlspecialchars($a['headline'],ENT_QUOTES,'UTF-8').'</a></h2><p>'.htmlspecialchars($a['summary'],ENT_QUOTES,'UTF-8').'</p><p><small>Source: '.htmlspecialchars($a['source_name'],ENT_QUOTES,'UTF-8').'</small></p>';$html.='<p><a href="https://www.normanandcompany.com/unsubscribe-news.php?token='.rawurlencode($token).'">Disable this news alert</a></p></body></html>';
  $status='prepared';if(getenv('NEWS_MAIL_TRANSPORT')==='mail'){$headers="MIME-Version: 1.0\r\nContent-type: text/html; charset=UTF-8\r\nFrom: ".(getenv('NEWS_FROM_EMAIL')?:'news@normanandcompany.com');$status=@mail($alert['email_address'],$alert['alert_name'],$html,$headers)?'sent':'failed';}elseif($directory=getenv('NEWS_DIGEST_EXPORT_DIR')){if((is_dir($directory)||@mkdir($directory,0750,true))&&@file_put_contents(rtrim($directory,'/').'/digest-'.$alert['id'].'-'.date('YmdHis').'.html',$html)!==false)$status='exported';}
  $pdo->prepare('INSERT INTO user_news_digest_history(user_id,alert_id,period_start,period_end,article_count,article_ids_json,status,sent_at,error_message) VALUES(:user,:alert,:start,NOW(),:count,:ids,:status,IF(:status2="sent",NOW(),NULL),NULL)')->execute([':user'=>$alert['user_id'],':alert'=>$alert['id'],':start'=>$start,':count'=>count($ids),':ids'=>json_encode($ids),':status'=>$status,':status2'=>$status]);if($status!=='failed'){$pdo->prepare('UPDATE user_news_alerts SET last_sent_at=NOW() WHERE id=:id')->execute([':id'=>$alert['id']]);$sent++;}}
 $pdo->query("SELECT RELEASE_LOCK('norman_news_digest')");fwrite(STDOUT,"Prepared {$sent} news digests.\n");exit(0);
}catch(Throwable $e){fwrite(STDERR,"Digest worker failed: ".$e->getMessage()."\n");exit(1);}
